[2023-12-01T21:57:51.549+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.transform_data manual__2023-12-01T21:57:41.700289+00:00 [queued]>
[2023-12-01T21:57:51.591+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.transform_data manual__2023-12-01T21:57:41.700289+00:00 [queued]>
[2023-12-01T21:57:51.594+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-01T21:57:51.650+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): transform_data> on 2023-12-01 21:57:41.700289+00:00
[2023-12-01T21:57:51.667+0000] {standard_task_runner.py:57} INFO - Started process 18345 to run task
[2023-12-01T21:57:51.677+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'transform_data', 'manual__2023-12-01T21:57:41.700289+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmpvq6jivz9']
[2023-12-01T21:57:51.679+0000] {standard_task_runner.py:85} INFO - Job 122: Subtask transform_data
[2023-12-01T21:57:51.845+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.transform_data manual__2023-12-01T21:57:41.700289+00:00 [running]> on host 227737b5950b
[2023-12-01T21:57:52.040+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T21:57:41.700289+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T21:57:41.700289+00:00'
[2023-12-01T21:57:52.042+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T21:57:52.042+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'awk -F"," { print $1","$2","$3","toupper($4)","$5","$6","$7","$8","$9; } < /opt/***/logs/extracted_data.cv > /opt/***/logs/transformed_data.csv']
[2023-12-01T21:57:52.074+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T21:57:52.079+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `('
[2023-12-01T21:57:52.080+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `awk -F"," { print $1","$2","$3","toupper($4)","$5","$6","$7","$8","$9; } < /opt/***/logs/extracted_data.cv > /opt/***/logs/transformed_data.csv'
[2023-12-01T21:57:52.080+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-01T21:57:52.100+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-01T21:57:52.104+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=transform_data, execution_date=20231201T215741, start_date=20231201T215751, end_date=20231201T215752
[2023-12-01T21:57:52.123+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 122 for task transform_data (Bash command failed. The command returned a non-zero exit code 2.; 18345)
[2023-12-01T21:57:52.155+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T21:57:52.180+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
