[2023-12-01T20:43:56.399+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T20:43:51.367483+00:00 [queued]>
[2023-12-01T20:43:56.416+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T20:43:51.367483+00:00 [queued]>
[2023-12-01T20:43:56.417+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-01T20:43:56.444+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract_data_from_csv> on 2023-12-01 20:43:51.367483+00:00
[2023-12-01T20:43:56.455+0000] {standard_task_runner.py:57} INFO - Started process 17252 to run task
[2023-12-01T20:43:56.460+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'extract_data_from_csv', 'manual__2023-12-01T20:43:51.367483+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmp929dyu4x']
[2023-12-01T20:43:56.462+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask extract_data_from_csv
[2023-12-01T20:43:56.542+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T20:43:51.367483+00:00 [running]> on host 227737b5950b
[2023-12-01T20:43:56.662+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='extract_data_from_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T20:43:51.367483+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T20:43:51.367483+00:00'
[2023-12-01T20:43:56.663+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T20:43:56.664+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cut -d","  -f1,2,3,4 /opt/***/logs/vehicle-data.csv > /opt/***/logs/csv_data.csv']
[2023-12-01T20:43:56.688+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T20:43:56.696+0000] {subprocess.py:93} INFO - cut: /opt/***/logs/vehicle-data.csv: No such file or directory
[2023-12-01T20:43:56.697+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-01T20:43:56.714+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-01T20:43:56.719+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=extract_data_from_csv, execution_date=20231201T204351, start_date=20231201T204356, end_date=20231201T204356
[2023-12-01T20:43:56.736+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 104 for task extract_data_from_csv (Bash command failed. The command returned a non-zero exit code 1.; 17252)
[2023-12-01T20:43:56.763+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T20:43:56.799+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
