[2023-12-01T20:41:13.581+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T01:36:01.257753+00:00 [queued]>
[2023-12-01T20:41:13.763+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T01:36:01.257753+00:00 [queued]>
[2023-12-01T20:41:13.764+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 4
[2023-12-01T20:41:13.918+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract_data_from_csv> on 2023-12-01 01:36:01.257753+00:00
[2023-12-01T20:41:13.948+0000] {standard_task_runner.py:57} INFO - Started process 17206 to run task
[2023-12-01T20:41:13.956+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'extract_data_from_csv', 'manual__2023-12-01T01:36:01.257753+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/ETL_toll_data.py', '--cfg-path', '/tmp/tmppieoi9c3']
[2023-12-01T20:41:13.961+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask extract_data_from_csv
[2023-12-01T20:41:14.260+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_toll_data.extract_data_from_csv manual__2023-12-01T01:36:01.257753+00:00 [running]> on host 227737b5950b
[2023-12-01T20:41:14.800+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chibuikeokenu@gmail.com' AIRFLOW_CTX_DAG_OWNER='Golstine' AIRFLOW_CTX_DAG_ID='ETL_toll_data' AIRFLOW_CTX_TASK_ID='extract_data_from_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T01:36:01.257753+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-01T01:36:01.257753+00:00'
[2023-12-01T20:41:14.821+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-01T20:41:14.858+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cut -d","  -f1,2,3,4 /opt/***/logs/vehicle-data.csv > /opt/***/logs/csv_data.csv']
[2023-12-01T20:41:14.910+0000] {subprocess.py:86} INFO - Output:
[2023-12-01T20:41:14.920+0000] {subprocess.py:93} INFO - cut: /opt/***/logs/vehicle-data.csv: No such file or directory
[2023-12-01T20:41:14.925+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-01T20:41:15.017+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-01T20:41:15.032+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_toll_data, task_id=extract_data_from_csv, execution_date=20231201T013601, start_date=20231201T204113, end_date=20231201T204115
[2023-12-01T20:41:15.091+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task extract_data_from_csv (Bash command failed. The command returned a non-zero exit code 1.; 17206)
[2023-12-01T20:41:15.179+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-01T20:41:15.260+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
